baseURL = 'https://jmjoy.github.io/'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'
title = "jmjoy's blog"
theme = 'hugo-theme-reimu'

[languages]
  [languages.zh-CN]
    languageName = '简体中文'
    weight = 1

[params]
menu = [
    { name = "home", url = "", icon = "1F3E0" },
    { name = "archives", url = "archives", icon = "1F5C4" },
    { name = "about", url = "about", icon = "2139" },
]
mainSections = ["posts"]
author = "jmjoy"
description = "jmjoy's blog"
subtitle = "要做的事还有很多_"
banner = "images/banner.webp"
preloader = { enable = false }
firework = { enable = false }
open_graph = { enable = false }
footer = { since = "2024", powered = true, count = false, busuanzi = false, icon = { url = "", rotate = true, mask = true } }
sidebar = "right"
