baseURL = 'https://jmjoy.github.io/'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'
title = "jmjoy's blog"
theme = 'hugo-theme-reimu'

[languages]
  [languages.zh-CN]
    languageName = '简体中文'
    weight = 1

[params]
menu = [
    { name = "home", url = "", icon = "f015" },
    { name = "archives", url = "archives", icon = "f01c" },
    { name = "about", url = "about", icon = "f05a" },
]
mainSections = ["posts"]
author = "jmjoy"
description = "jmjoy's blog"
subtitle = "要做的事还有很多_"
banner = "images/banner.webp"
preloader = { enable = false }
reimu_cursor = false
# firework = { enable = false }
open_graph = { enable = false }
sidebar = "right"
icon_font = false

[params.algolia_search]
enable = true
appID = "C2ET8LMPF9"
apiKey = "b0adabfaae28860ec6dd0d9896530884"
indexName = "algolia"

[params.footer]
since = "2024"
powered = true
count = false
busuanzi = false

[params.footer.icon]
url = "../images/copyright.webp"
rotate = false
mask = false

[params.top.icon]
url = "../images/top.webp"
rotate = false
mask = false

[params.giscus]
enable = true
repo = "jmjoy/jmjoy.github.io"
repoId = "MDEwOlJlcG9zaXRvcnk1MTA3ODg4Mw=="
category = "Announcements"
categoryId = "DIC_kwDOAwtm484Clhbw"
mapping = "mapping"
strict = 0
reactionsEnabled = 1
emitMetadata = 0
inputPosition = "bottom"
lang = "zh-CN"

[params.social]
github = "https://github.com/jmjoy"

[markup.highlight]
guessSyntax = true
noClasses = false

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
